# Generated by Django 3.2.20 on 2023-09-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='article_text_short',
            field=models.TextField(blank=True, null=True),
        ),
    ]
