# Generated by Django 3.2.20 on 2023-09-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogpost_article_text_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='article_text',
            field=models.TextField(default='none'),
        ),
    ]
