# Generated by Django 3.2.20 on 2023-09-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
