# Generated by Django 3.2.20 on 2023-09-24 18:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImageName', models.ImageField(upload_to='full/')),
                ('productImageNameFull', models.ImageField(upload_to='full/')),
                ('productImageNameSmall', models.ImageField(upload_to='small/')),
                ('titleHTML', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('priceHTML', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('skuHTML', models.CharField(max_length=2000)),
                ('sku', models.CharField(max_length=200)),
                ('descriptionHTML', models.TextField()),
                ('description', models.TextField()),
                ('liquidHTML', models.TextField(blank=True)),
                ('liquid', models.TextField(blank=True)),
                ('productImageLink', models.TextField(blank=True, null=True)),
                ('productImageLinks', models.TextField(blank=True, null=True)),
                ('productKey', models.CharField(blank=True, max_length=250, null=True)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_products', to=settings.AUTH_USER_MODEL)),
                ('productCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
