# Generated by Django 3.2.20 on 2023-09-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImageName',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='full/'),
        ),
    ]
