# Generated by Django 3.2.20 on 2023-09-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_productimagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImageNameFull',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='full/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productImageNameSmall',
            field=models.ImageField(blank=True, default='noimage.png', upload_to='small/'),
        ),
    ]
