# Generated by Django 3.2.20 on 2023-09-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20230902_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImageName', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('liquid', models.TextField(blank=True)),
                ('productImageLink', models.TextField()),
                ('productImageLinks', models.TextField()),
                ('productKey', models.CharField(max_length=250, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
