# Generated by Django 3.2.20 on 2023-09-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
